import { Machine } from '../models/machines.interface';

// This is hardcoded data that represents an searchable index of machines
export const mockMachines: Machine[] = [
  {
    id: 1,
    name: 'Cricut Maker 3',
    description:
      'With more power & tools, on top of custom cards, stickers & big banners up to 12 feet, you can cut fabrics, engrave metal, deboss leather & so much more.',
    tags: {
      projectTags: [
        'Vinyl decals',
        'Written labels',
        'Cards',
        'Gift tags',
        'Custom mugs',
        'Full-color stickers',
        'Personalized apparel',
        'Banners',
        'Gift boxes',
        'Signs',
        'Jewelry',
        'Wood decor',
        'Quilts',
        'Engraved metal tags',
      ],
      cutTypeTags: [
        'Cut',
        'Write',
        'Draw',
        'Foil',
        'Score',
        'Deboss',
        'Engrave',
        'Perforate',
      ],
      toolTags: [
        'Premium Fine-Point Blade',
        'Foil Transfer Tool',
        'Pens & Markers',
        'Scoring Stylus',
        'Bonded-Fabric Blade',
        'Scoring Wheels (Single & Double)',
        'Rotary Blade',
        'Wavy Blade',
        'Knife Blade',
        'Engraving Tip',
        'Debossing Tip',
        'Perforation Blade',
      ],
      materialTags: [
        'Acetate',
        'Adhesive Foil',
        'Adhesive Foil, Matte',
        'Adhesive Sheet, Double-Sided',
        'Aluminum Foil',
        'Art/Illustration Board',
        'Balsa - 1/16 (1.6 mm)',
        'Balsa - 3/32 (2.4 mm)',
        'Bamboo Fabric',
        'Basswood - 1/16 (1.6 mm)',
        'Basswood - 1/32 (0.8 mm)',
        'Bengaline',
        'Birch, Permanent Adhesive',
        'Boucle',
        'Broadcloth',
        'Burlap',
        'Burn-Out Velvet',
        'Butcher Paper',
        'Calibration Paper',
        'Calico',
        'Cambric',
        'Canvas',
        'Carbon Fiber',
        'Cardstock (for intricate cuts)',
        'Cardstock, Adhesive-Backed',
        'Cashmere',
        'Cereal Box',
        'Chalkboard Vinyl',
        'Challis',
        'Chambray',
        'Chantilly Lace',
        'Charmeuse Satin',
        'Chiffon',
        'Chintz',
        'Chipboard (1.5 mm)',
        'Colored Duct Tape',
        'Construction Paper',
        'Copy Paper  20 lb (75 gsm)',
        'Copy Paper  24 lb (90 gsm)',
        'Copy Paper  32 lb (120 gsm)',
        'Corduroy',
        'Corrugated Cardboard',
        'Corrugated Paper',
        'Cotton',
        'Cotton, Bonded',
        'Craft Foam',
        'Crepe Charmeuse',
        'Crepe de Chine',
        'Crepe Paper',
        'Crepe-back Satin',
        'Cutaway Card + Backer',
        'Cutting Mat Protector',
        'Damask',
        'Delicate Fabrics (like Tulle)',
        'Delicate Fabrics (like Tulle), Bonded',
        'Deluxe Paper',
        'Deluxe Paper Foil Embossed',
        'Deluxe Paper, Adhesive Backed',
        'Denim',
        'Denim, Bonded',
        'Dotted Swiss',
        'Double Cloth',
        'Double Knit',
        'Dry Erase Vinyl',
        'Duck Cloth',
        'Duct Tape Sheet',
        'Dupioni Silk',
        'EVA Foam',
        'Everyday Iron-On',
        'Everyday Iron-On Mesh',
        'Everyday Iron-On Mosaic',
        'Express Iron-On',
        'Extra Heavy Fabrics (like Burlap)',
        'Eyelet',
        'Faille',
        'Faux Fur',
        'Faux Leather (Paper Thin)',
        'Faux Suede',
        'Faux Suede',
        'Felt',
        'Felt, Acrylic Fabric',
        'Felt, Craft Bonded',
        'Felt, Glitter Bonded',
        'Felt, Stiff',
        'Felt, Wool Bonded',
        'Felt, Wool Fabric',
        'Flannel',
        'Flat Cardboard',
        'Fleece',
        'Flex Foam',
        'Flocked Iron-On',
        'Flocked Paper',
        'Foil Acetate',
        'Foil Iron-On',
        'Foil Kraft Board  Holographic',
        'Foil Paper  0.36mm',
        'Foil Poster Board',
        'Foil Tape - Shiny Side Down',
        'Foil Tape - Shiny Side Up',
        'Foulard',
        'Freezer Paper',
        'Fusible Fabric',
        'Fusible Fleece',
        'Fusible Interfacing',
        'Gabardine',
        'Gauze',
        'Gel Sheet',
        'Genuine Leather',
        'Georgette',
        'Glitter Cardstock',
        'Glitter Craft Foam',
        'Glitter Duct Tape',
        'Glitter Iron-On',
        'Glitter Mesh Iron-On',
        'Glitter Vinyl',
        'Gossamer',
        'Grocery Bag',
        'Grois Point',
        'Grosgrain',
        'Habutai',
        'Handmade Paper',
        'Heat Transfer (non-Cricut)',
        'Heather',
        'Heavy Cardstock  100 lb. (270 gsm)',
        'Heavy Chipboard  2.0mm',
        'Heavy Fabrics (like Denim)',
        'Heavy Fabrics (like Denim), Bonded',
        'Heavy Patterned Paper',
        'Heavy Watercolor Paper  140 lb (300 gsm)',
        'Holographic Cardstock',
        'Holographic Heat Transfer',
        'Holographic Iron-On',
        'Holographic Iron-On Mosaic',
        'Holographic Sparkle Iron-On',
        'Holographic Sparkle Iron-On Mosaic',
        'Homespun Fabric',
        'Infusible Ink Transfer Sheet',
        'Insulbrite Batting',
        'Interlock Knit',
        'Jacquard',
        'Jersey',
        'Jute',
        'Kevlar',
        'Khaki',
        'Kraft Board',
        'Kraft Cardstock',
        'La Coste',
        'Lame',
        'Laser Copy Paper',
        'Light Cardstock  60 lb (163 gsm)',
        'Light Chipboard  0.37mm',
        'Light Cotton',
        'Light Cotton, 2 layers',
        'Light Cotton, 3 layers',
        'Light Fabrics (like Silk)',
        'Light Fabrics (like Silk), Bonded',
        'Light Patterned Paper',
        'Linen',
        'Linen, Bonded',
        'Lycra',
        'Magnetic Sheet  1.0 mm',
        'Magnetic Sheet  0.5 mm',
        'Matboard (1.5 mm)',
        'Matelasse',
        'Matte Vinyl',
        'Medium Cardstock  80 lb (216 gsm)',
        'Medium Fabrics (like Cotton)',
        'Medium Fabrics (like Cotton), Bonded',
        'Medium Garment Leather  4-5 oz. (1.6 mm)',
        'Melton Wool',
        'Mesh',
        'Metallic Iron-On Mosaic',
        'Metallic Leather',
        'Metallic Poster Board',
        'Metallic Vinyl',
        'Microfiber',
        'Moiree',
        'Moleskin',
        `Monk's Cloth`,
        'Mulberry Paper',
        'Muslin',
        'Mylar',
        'Natural Wood Veneer',
        'Neoprene',
        'Non-Adhesive Vinyl  16 gauge',
        'Non-Adhesive Vinyl  20 gauge',
        'Notebook Paper',
        'Nylon',
        'Oil Cloth, Bonded',
        'Oilcloth',
        'Organza',
        'Ottoman',
        'Outdoor Vinyl, Bonded',
        'Oxford',
        'Paint Chip',
        'Panne Velvet',
        'Paper, Adhesive-Backed',
        'Parchment Paper',
        'Party Foil',
        'Patterned Glitter Cardstock',
        'Patterned Iron-On',
        'Pearl Paper',
        'Peau de Soie',
        'Photo Paper',
        'Pima Cotton',
        'Pique Cotton',
        'Plastic Canvas',
        'Plastic Packaging',
        'Plisse',
        'Plush',
        'Polyester',
        'Polyester, Bonded',
        'Poplin',
        'Poster Board',
        'Premium Outdoor Vinyl',
        'Premium Vinyl - Permanent Glossy',
        'Premium Vinyl - Removable Matte',
        'Premium Vinyl - Frosted Glitter',
        'Premium Vinyl - Frosted Gray',
        'Premium Vinyl - Frosted Opaque',
        'Premium Vinyl - Holographic',
        'Premium Vinyl - Holographic 3D Texture',
        'Premium Vinyl - Holographic Art Deco',
        'Premium Vinyl - Holographic Bubbles',
        'Premium Vinyl - Holographic Crystals',
        'Premium Vinyl - Holographic Rose Bubble',
        'Premium Vinyl - Holographic Threads',
        'Premium Vinyl - Mosaic',
        'Premium Vinyl - Pearl',
        'Premium Vinyl - Shimmer',
        'Premium Vinyl - Textured',
        'Premium Vinyl - Textured Metallic',
        'Premium Vinyl - True Brushed',
        'Printable Fabric',
        'Printable Foil',
        'Printable Iron-On, Dark',
        'Printable Iron-On, Light',
        'Printable Magnetic Sheet',
        'Printable Sticker Paper, Clear (No Liner Printing)',
        'Printable Sticker Paper, White (Gray Liner Printing)',
        'Printable Sticker Paper, White (Green Liner Printing)',
        'Printable Vinyl, Specialty',
        'Printable Vinyl, Transparent',
        'Printable Vinyl, White (Gray Liner Printing)',
        'Printable Vinyl, White (Green Liner Printing)',
        'Printable Waterproof Sticker Set - Transparent',
        'Printable Waterproof Sticker Set - Transparent Holographic',
        'Printable Waterproof Sticker Set - White',
        'Printable Waterproof Sticker Set - White Holographic',
        'Quilt Batting',
        'Ramie',
        'Raschel Knit',
        'Rayon Lyocell',
        'Rib Knit',
        'Rice Paper',
        'Rip-Stop Nylon',
        'Sailcloth',
        'Sandblast Stencil',
        'Satin Silk',
        'Seersucker',
        'Sequined',
        'Shantung',
        'Shantung Santeen',
        'Shimmer Leather  1mm',
        'Shimmer Paper',
        'Silk China',
        'Silk, Bonded',
        'Slinky Knit',
        'Smart Iron-On',
        'Smart Iron-On  Glitter',
        'Smart Iron-On  Holographic',
        'Smart Paper, Sticker Cardstock',
        'Smart Vinyl  Matte Metallic',
        'Smart Vinyl  Permanent',
        'Smart Vinyl  Removable',
        'Smart Vinyl  Shimmer',
        'Smooth Glitter Paper',
        'Spandex',
        'Sparkle Paper',
        'SportFlex Iron-On',
        'Stencil Film  0.4mm',
        'Stencil Vinyl',
        'Sticker Paper, Removable',
        'Sticky Note',
        'Suede',
        'Tafetta',
        'Terry Cloth',
        'Thin Garment Leather  2-3 oz. (0.8-1.3 mm)',
        'Tissue Paper',
        'Tooling Leather  2-3 oz. (0.8 mm)',
        'Tooling Leather  4-5 oz. (1.6 mm)',
        'Tooling Leather  6-7 oz. (2.4 mm)',
        'Transfer Foil',
        'Transfer Sheet',
        'Transparency',
        'True Brushed Paper',
        'Tulle',
        'Tweed',
        'Ultra Firm Stabilizer',
        'Vellum',
        'Velour',
        'Velvet Upholstery',
        'Velveteen',
        'Vinyl',
        'Viscose',
        'Waffle Cloth',
        'Washi Sheet',
        'Washi Tape  0.06 mm',
        'Wax Paper',
        'Window Cling',
        'Wool Crepe',
        'Wrapping Paper',
        'Ziberline',
      ],
      specTags: ['Bluetooth', 'USB', 'iOS', 'Mac', 'Windows', 'Android'],
    },
    image:
      'https://cricut.com/on/demandware.static/-/Library-Sites-cricut-content-na01/default/dw73772912/images/comparison/cricutMaker3/machine/Machine_Cricut_Maker3_Desktop.jpg',
    url: 'https://cricut.com/en-us/cutting-machines/cricut-maker/cricut-maker-3/cricut-maker-3/2008334.html',
  },
  {
    id: 2,
    name: 'Cricut Explore 3',
    description:
      'For the crafter looking to make popular projects like custom apparel, home decor & more. You can even make festive banners up to 12 feet long.',
    tags: {
      projectTags: [
        'Vinyl decals',
        'Written labels',
        'Cards',
        'Gift tags',
        'Custom mugs',
        'Full-color stickers',
        'Personalized apparel',
        'Banners',
        'Gift boxes',
        'Signs',
        'Jewelry',
      ],
      cutTypeTags: ['Cut', 'Write', 'Draw', 'Foil', 'Score'],
      toolTags: [
        'Premium Fine-Point Blade',
        'Foil Transfer Tool',
        'Pens & Markers',
        'Scoring Stylus',
        'Bonded-Fabric Blade',
      ],
      materialTags: [
        'Adhesive Foil',
        'Adhesive Foil, Matte',
        'Aluminum Foil',
        'Butcher Paper',
        'Calibration Paper',
        'Cardstock (for intricate cuts)',
        'Cardstock, Adhesive Backed',
        'Chalkboard Vinyl',
        'Construction Paper',
        'Copy Paper 20 lb (75 gsm)',
        'Copy Paper 24lb (90 gsm)',
        'Copy Paper 32 lb (120 gsm)',
        'Corrugated Cardboard',
        'Craft Foam',
        'Cutaway Card + Backer',
        'Cutting Mat Protector',
        'Deluxe Paper',
        'Deluxe Paper Foil Embossed',
        'Deluxe Paper, Adhesive Backed',
        'Denim, Bonded*',
        'Duct Tape Sheet',
        'EVA Foam',
        'Everyday Iron-On',
        'Everyday Iron-On Mesh',
        'Everyday Iron-On Mosaic',
        'Express Iron-On',
        'Faux Leather (Paper Thin)',
        'Faux Suede',
        'Felt, Wool Bonded*',
        'Felt, Wool Fabric',
        'Flat Cardboard',
        'Flexible Stencil Film',
        'Flocked Paper',
        'Foil Acetate',
        'Foil Iron-On',
        'Foil Kraft Board - Holographic',
        'Foil Paper - 0.36mm',
        'Foil Poster Board',
        'Fusible Fabric',
        'Genuine Leather',
        'Glitter Cardstock',
        'Glitter Craft Foam',
        'Glitter Iron-On',
        'Glitter Mesh Iron-On',
        'Glitter Vinyl',
        'Grocery Bag',
        'Heavy Cardstock-100 lb (270 gsm)',
        'Heavy Patterned Paper',
        'Heavy Watercolor Paper - 140 lb (300 gsm)',
        'Holographic Iron-On',
        'Holographic Iron-On Mosaic',
        'Holographic Sparkle Iron-On',
        'Holographic Sparkle Iron-On Mosaic',
        'Holographic Sparkle Vinyl',
        'Infusible Ink Transfer Sheet',
        'Insert Card Cardstock',
        'Kraft Board',
        'Kraft Cardstock',
        'Laser Copy Paper',
        'Light Cardstock 65 lb (176 gsm)',
        'Light Chipboard - 0.37mm',
        'Light Patterned Paper',
        'Magnetic Sheet - 1.0 mm',
        'Magnetic Sheet - 0.5 mm',
        'Matboard (1.5 mm)',
        'Medium Cardstock - 80 lb (216 gsm)',
        'Metallic Iron-On Mosaic',
        'Metallic Leather',
        'Metallic Poster Board',
        'Mylar',
        'Natural Wood Veneer',
        'Notebook Paper',
        'Oil Cloth, Bonded*',
        'Paint Chip',
        'Parchment Paper',
        'Party Foil',
        'Patterned Iron-On',
        'Pearl Paper',
        'Photo Paper',
        'Polyester, Bonded*',
        'Premium Outdoor Vinyl',
        'Premium Vinyl - Permanent Glossy',
        'Premium Vinyl - Removable Matte',
        'Premium Vinyl-Frosted Glitter',
        'Premium Vinyl-Frosted Gray',
        'Premium Vinyl-Frosted Opaque',
        'Premium Vinyl-Holographic',
        'Premium Vinyl-Holographic 3D Texture',
        'Premium Vinyl-Holographic Art Deco',
        'Premium Vinyl-Holographic Bubbles',
        'Premium Vinyl-Holographic Crystals',
        'Premium Vinyl-Holographic Rose Bubble',
        'Premium Vinyl-Holographic Threads',
        'Premium Vinyl-Mosaic',
        'Premium Vinyl-Pearl',
        'Premium Vinyl-Shimmer',
        'Premium Vinyl-Textured',
        'Premium Vinyl-Textured Metallic',
        'Premium Vinyl-True Brushed',
        'Printable Fabric',
        'Printable Iron-On, Dark',
        'Printable Iron-On, Light',
        'Printable Sticker Paper, Clear (No Liner Printing)',
        'Printable Sticker Paper, White (Gray Liner Printing)',
        'Printable Sticker Paper, White (Green Liner Printing)',
        'Printable Vinyl, Specialty',
        'Printable Vinyl, Transparent',
        'Printable Vinyl, White (Gray Liner Printing)',
        'Printable Vinyl, White (Green Liner Printing)',
        'Printable Waterproof Sticker Set - Transparent',
        'Printable Waterproof Sticker Set - Transparent Holographic',
        'Printable Waterproof Sticker Set - White',
        'Printable Waterproof Sticker Set - White Holographic',
        'Reflective Iron-On',
        'Shimmer Leather - 1 mm',
        'Shimmer Paper',
        'Silk, Bonded*',
        'Smart Iron-On',
        'Smart Iron-On Glitter',
        'Smart Iron-On Holographic',
        'Smart Paper, Sticker Cardstock',
        'Smart Vinyl Matte Metallic',
        'Smart Vinyl Permanent',
        'Smart Vinyl Removable',
        'Smart Vinyl Shimmer',
        'Smooth Glitter Paper',
        'Sparkle Paper',
        'SportFlex Iron-On',
        'Stencil Film - 0.4mm',
        'Stencil Vinyl',
        'Sticky Note',
        'Tattoo Paper',
        'Transparency',
        'True Brushed Paper',
        'Vellum',
        'Washi Sheet',
        'Washi Tape - 0.06mm',
        'Wax Paper',
        'Window Cling',
        'Wrapping Paper',
        'Interlock Knit',
        'Jacquard',
        'Jersey',
        'Jute',
        'Kevlar',
        'Khaki',
        'Kraft Board',
        'Kraft Cardstock',
        'La Coste',
        'Lame',
        'Laser Copy Paper',
        'Light Cardstock 60 lb (163 gsm)',
        'Light Chipboard 0.37mm',
        'Light Cotton',
        'Light Cotton, 2 layers',
        'Light Cotton, 3 layers',
        'Light Fabrics (like Silk)',
        'Light Fabrics (like Silk), Bonded',
        'Light Patterned Paper',
        'Linen',
        'Linen, Bonded',
        'Lycra',
        'Magnetic Sheet 1.0 mm',
        'Magnetic Sheet 0.5 mm',
        'Matboard (1.5 mm)',
        'Matelasse',
        'Matte Vinyl',
        'Medium Cardstock 80 lb (216 gsm)',
        'Medium Fabrics (like Cotton)',
        'Medium Fabrics (like Cotton), Bonded',
        'Medium Garment Leather 4-5 oz. (1.6 mm)',
        'Melton Wool',
        'Mesh',
        'Metallic Iron-On Mosaic',
        'Metallic Leather',
        'Metallic Poster Board',
        'Metallic Vinyl',
        'Microfiber',
        'Moiree',
        'Moleskin',
        `Monk's Cloth`,
        'Mulberry Paper',
        'Muslin',
        'Mylar',
        'Natural Wood Veneer',
        'Neoprene',
        'Non-Adhesive Vinyl 16 gauge',
        'Non-Adhesive Vinyl 20 gauge',
        'Notebook Paper',
        'Nylon',
        'Oil Cloth, Bonded',
        'Oilcloth',
        'Organza',
        'Ottoman',
        'Outdoor Vinyl, Bonded',
        'Oxford',
        'Paint Chip',
        'Panne Velvet',
        'Paper, Adhesive-Backed',
        'Parchment Paper',
        'Party Foil',
        'Patterned Glitter Cardstock',
        'Patterned Iron-On',
        'Pearl Paper',
        'Peau de Soie',
        'Photo Paper',
        'Pima Cotton',
        'Pique Cotton',
        'Plastic Canvas',
        'Plastic Packaging',
        'Plisse',
        'Plush',
        'Polyester',
        'Polyester, Bonded',
        'Poplin',
        'Poster Board',
        'Premium Outdoor Vinyl',
        'Premium Vinyl - Permanent Glossy',
        'Premium Vinyl - Removable Matte',
        'Premium Vinyl - Frosted Glitter',
        'Premium Vinyl - Frosted Gray',
        'Premium Vinyl - Frosted Opaque',
        'Premium Vinyl - Holographic',
        'Premium Vinyl - Holographic 3D Texture',
        'Premium Vinyl - Holographic Art Deco',
        'Premium Vinyl - Holographic Bubbles',
        'Premium Vinyl - Holographic Crystals',
        'Premium Vinyl - Holographic Rose Bubble',
        'Premium Vinyl - Holographic Threads',
        'Premium Vinyl - Mosaic',
        'Premium Vinyl - Pearl',
        'Premium Vinyl - Shimmer',
        'Premium Vinyl - Textured',
        'Premium Vinyl - Textured Metallic',
        'Premium Vinyl - True Brushed',
        'Printable Fabric',
        'Printable Foil',
        'Printable Iron-On, Dark',
        'Printable Iron-On, Light',
        'Printable Magnetic Sheet',
        'Printable Sticker Paper, Clear (No Liner Printing)',
        'Printable Sticker Paper, White (Gray Liner Printing)',
        'Printable Sticker Paper, White (Green Liner Printing)',
        'Printable Vinyl, Specialty',
        'Printable Vinyl, Transparent',
        'Printable Vinyl, White (Gray Liner Printing)',
        'Printable Vinyl, White (Green Liner Printing)',
        'Printable Waterproof Sticker Set - Transparent',
        'Printable Waterproof Sticker Set - Transparent Holographic',
        'Printable Waterproof Sticker Set - White',
        'Printable Waterproof Sticker Set - White Holographic',
        'Quilt Batting',
        'Ramie',
        'Raschel Knit',
        'Rayon Lyocell',
        'Rib Knit',
        'Rice Paper',
        'Rip-Stop Nylon',
        'Sailcloth',
        'Sandblast Stencil',
        'Satin Silk',
        'Seersucker',
        'Sequined',
        'Shantung',
        'Shantung Santeen',
        'Shimmer Leather 1mm',
        'Shimmer Paper',
        'Silk China',
        'Silk, Bonded',
        'Slinky Knit',
        'Smart Iron-On',
        'Smart Iron-On Glitter',
        'Smart Iron-On Holographic',
        'Smart Paper, Sticker Cardstock',
        'Smart Vinyl Matte Metallic',
        'Smart Vinyl Permanent',
        'Smart Vinyl Removable',
        'Smart Vinyl Shimmer',
        'Smooth Glitter Paper',
        'Spandex',
        'Sparkle Paper',
        'SportFlex Iron-On',
        'Stencil Film 0.4mm',
        'Stencil Vinyl',
        'Sticker Paper, Removable',
        'Sticky Note',
        'Suede',
        'Tafetta',
        'Terry Cloth',
        'Thin Garment Leather 2-3 oz. (0.8-1.3 mm)',
        'Tissue Paper',
        'Tooling Leather 2-3 oz. (0.8 mm)',
        'Tooling Leather 4-5 oz. (1.6 mm)',
        'Tooling Leather 6-7 oz. (2.4 mm)',
        'Transfer Foil',
        'Transfer Sheet',
        'Transparency',
        'True Brushed Paper',
        'Tulle',
        'Tweed',
        'Ultra Firm Stabilizer',
        'Vellum',
        'Velour',
        'Velvet Upholstery',
        'Velveteen',
        'Vinyl',
        'Viscose',
        'Waffle Cloth',
        'Washi Sheet',
        'Washi Tape 0.06 mm',
        'Wax Paper',
        'Window Cling',
        'Wool Crepe',
        'Wrapping Paper',
        'Ziberline',
      ],
      specTags: ['Bluetooth', 'USB', 'iOS', 'Mac', 'Windows', 'Android'],
    },
    image:
      'https://cricut.com/on/demandware.static/-/Library-Sites-cricut-content-na01/default/dwed21ef9a/images/comparison/cricutExplore3/machine/Machine_Cricut_Explore3_Desktop.jpg',
    url: 'https://cricut.com/en-us/cutting-machines/cricut-explore/cricut-explore-3/cricut-explore-3/2008337.html',
  },
  {
    id: 3,
    name: 'Cricut Joy Xtra',
    description:
      'Our fits-in-any-space cutting machine for popular projects like full-color stickers, custom cards, T-shirts & so much more.',
    tags: {
      projectTags: [
        'Vinyl decals',
        'Written labels',
        'Cards',
        'Gift tags',
        'Custom mugs',
        'Full-color stickers',
        'Personalized apparel',
      ],
      cutTypeTags: ['Cut', 'Write', 'Draw', 'Foil'],
      toolTags: [
        'Premium Fine-Point Blade',
        'Foil Transfer Tool',
        'Pens & Markers',
      ],
      materialTags: [
        'Adhesive Foil',
        'Calibration Paper',
        'Chalkboard Vinyl',
        'Cutaway Card + Backer',
        'Deluxe Paper',
        'Deluxe Paper Foil Embossed',
        'Dry Erase Vinyl',
        'Everyday Iron-On',
        'Everyday Iron-On Mesh',
        'Everyday Iron-On Mosaic',
        'Flexible Stencil Film',
        'Foil Acetate',
        'Foil Paper - 0.36 mm',
        'Foil Poster Board',
        'Glitter Cardstock',
        'Glitter Iron-On',
        'Glitter Mesh Iron-On',
        'Glow in the Dark Iron-On',
        'Glow in the Dark Vinyl',
        'Heat/Cold Activated Color Changing Vinyl',
        'Heavy Cardstock - 100 lb (270 gsm)',
        'Holographic Iron-On',
        'Holographic Iron-On Mosaic',
        'Holographic Sparkle Iron-On',
        'Holographic Sparkle Vinyl',
        'Infusible Ink Transfer Sheet',
        'Insert Card - Cardstock',
        'Laser Copy Paper',
        'Light Cardstock - 65 lb (176 gsm)',
        'Medium Cardstock - 80 lb (216 gsm)',
        'Photo Paper',
        'Premium Vinyl - Permanent Glossy',
        'Premium Vinyl - Removable Matte',
        'Premium Vinyl - Frosted Glitter',
        'Premium Vinyl - Frosted Opaque',
        'Premium Vinyl - Holographic Art Deco',
        'Premium Vinyl - Holographic Bubbles',
        'Premium Vinyl - Holographic Crystals',
        'Premium Vinyl - Holographic Rose Bubble',
        'Premium Vinyl - Holographic Threads',
        'Premium Vinyl - Mosaic',
        'Premium Vinyl - Pearl',
        'Premium Vinyl - Shimmer',
        'Premium Vinyl - Textured',
        'Premium Vinyl - Textured Metallic',
        'Premium Vinyl - True Brushed',
        'Printable Iron-On, Dark',
        'Printable Iron-On, Light',
        'Printable Sticker Paper, Clear (No Liner Printing)',
        'Printable Sticker Paper, White (Gray Liner Printing)',
        'Printable Sticker Paper, White (Green Liner Printing)',
        'Printable Vinyl, Specialty',
        'Printable Vinyl, Transparent',
        'Printable Vinyl, White (Gray Liner Printing)',
        'Printable Vinyl, White (Green Liner Printing)',
        'Printable Waterproof Sticker Set - Transparent',
        'Printable Waterproof Sticker Set - Transparent Holographic',
        'Printable Waterproof Sticker Set - White',
        'Printable Waterproof Sticker Set - White Holographic',
        'Reflective Iron-On',
        'Smart Iron-On',
        'Smart Iron-On - Holographic',
        'Smart Label Writable Paper',
        'Smart Label Writable Vinyl',
        'Smart Prismatic Glitter Iron-On',
        'Smart Vinyl - Matte Metallic',
        'Smart Vinyl - Permanent',
        'Smart Vinyl - Removable',
        'SportFlex Iron-On',
        'True Brushed Paper',
        'UV Activated Color Changing Iron-On',
        'Watercolor Cards',
      ],
      specTags: ['Bluetooth', 'iOS', 'Mac', 'Windows', 'Android'],
    },
    image:
      'https://cricut.com/on/demandware.static/-/Library-Sites-cricut-content-na01/default/dwbba0f990/images/comparison/cricutJoyXtra/machine/Machine_Cricut_Xtra_Desktop.jpg',
    url: 'https://cricut.com/en-us/cutting-machines/cricut-joy/cricut-joy-xtra/cricut-joy-xtra/2010313.html',
  },
  {
    id: 4,
    name: 'Cricut Joy',
    description:
      'Our most compact machine for fun and functional everyday projects like custom cards, simple decals & labels to organize anything and everything.',
    tags: {
      projectTags: [
        'Vinyl decals',
        'Written labels',
        'Cards',
        'Gift tags',
        'Custom mugs',
      ],
      cutTypeTags: ['Cut', 'Write', 'Draw', 'Foil'],
      toolTags: [
        'Premium Fine-Point Blade',
        'Foil Transfer Tool',
        'Pens & Markers',
      ],
      materialTags: [
        'Adhesive Foil',
        'Chalkboard Vinyl',
        'Corrugated Cardboard',
        'Cutaway Card + Backer',
        'Deluxe Paper',
        'Deluxe Paper Foil Embossed',
        'Deluxe Paper, Adhesive Backed',
        'Dry Erase Vinyl',
        'Everyday Iron-On',
        'Everyday Iron-On Mesh',
        'Everyday Iron-On Mosaic',
        'Faux Leather (Paper Thin)',
        'Flat Cardboard',
        'Foil Acetate',
        'Foil Paper - 0.36 mm',
        'Foil Poster Board',
        'Glitter Cardstock',
        'Glitter Iron-On',
        'Glitter Mesh Iron-On',
        'Glow in the Dark Iron-On',
        'Glow in the Dark Vinyl',
        'Heat/Cold Activated Color Changing Vinyl',
        'Heavy Cardstock - 100 lb (270 gsm)',
        'Holographic Iron-On',
        'Holographic Iron-On Mosaic',
        'Holographic Sparkle Iron-On',
        'Holographic Sparkle Vinyl',
        'Holographic Vinyl',
        'Infusible Ink Transfer Sheet',
        'Insert Card - Cardstock',
        'Iron-On',
        'Laser Copy Paper',
        'Light Cardstock - 65 lb (176 gsm)',
        'Medium Cardstock - 80 lb (216 gsm)',
        'Party Foil',
        'Pearl Paper',
        'Photo Paper',
        'Premium Vinyl',
        'Premium Vinyl Frosted Glitter',
        'Premium Vinyl Frosted Gray',
        'Premium Vinyl Frosted Opaque',
        'Premium Vinyl Holographic 3D Texture',
        'Premium Vinyl Holographic Art Deco',
        'Premium Vinyl Holographic Bubbles',
        'Premium Vinyl Holographic Crystals',
        'Premium Vinyl Holographic Threads',
        'Premium Vinyl Mosaic',
        'Premium Vinyl - Pearl',
        'Premium Vinyl Textured',
        'Premium Vinyl Textured Metallic',
        'Premium Vinyl True Brushed',
        'Reflective Iron-On',
        'Shimmer Paper',
        'Smart Dissolvable Labels',
        'Smart Iron-On',
        'Smart Iron-On - Glitter',
        'Smart Iron-On - Holographic',
        'Smart Iron-On Patterned',
        'Smart Label Writable Paper',
        'Smart Label Writable Vinyl',
        'Smart Paper Sticker Cardstock',
        'Smart Stencil',
        'Smart Vinyl Holographic Patterns',
        'Smart Vinyl Matte Metallic',
        'Smart Vinyl - Permanent',
        'Smart Vinyl - Removable',
        'Smart Vinyl - Shimmer',
        'Sparkle Paper',
        'SportFlex Iron-On',
        'Stencil Vinyl',
        'True Brushed Paper',
        'UV Activated Color Changing Iron-On',
        'Watercolor Cards',
        'Window Cling',
      ],
      specTags: ['Bluetooth', 'iOS', 'Mac', 'Windows', 'Android'],
    },

    image:
      'https://cricut.com/on/demandware.static/-/Library-Sites-cricut-content-na01/default/dw95bc18f9/images/comparison/cricutJoy/machine/Machine_Cricut_Joy_Desktop.jpg',
    url: 'https://cricut.com/en-us/cutting-machines/cricut-joy/cricut-joy/cricut-joy/2007991.html',
  },
  {
    id: 5,
    name: 'Cricut Venture',
    description:
      'Our wide-format professional cutting machine that works at commercial speeds. Make extra-large projects like big paper flowers and wall decals, plus batches of T-shirts, totes & more.',
    tags: {
      projectTags: [
        'Vinyl decals',
        'Written labels',
        'Cards',
        'Gift tags',
        'Custom mugs',
        'Full-color stickers',
        'Personalized apparel',
        'Banners',
        'Gift boxes',
        'Signs',
        'Jewelry',
        'Large paper flowers',
      ],
      cutTypeTags: ['Cut', 'Write', 'Draw', 'Foil', 'Score'],
      toolTags: [
        'Premium Fine-Point Blade',
        'Foil Transfer Tool',
        'Pens & Markers',
        'Scoring Stylus',
        'Bonded-Fabric Blade',
      ],
      materialTags: [
        'Adhesive Foil',
        'Adhesive Foil, Matte',
        'Butcher Paper',
        'Cardstock (for intricate cuts)',
        'Cardstock, Adhesive-Backed',
        'Chalkboard Vinyl',
        'Construction Paper',
        'Copy Paper 20 lb (75 gsm)',
        'Copy Paper 32 lb (120 gsm)',
        'Craft Foam',
        'Cutaway Card + Backer',
        'Deluxe Paper Foil Embossed',
        'Deluxe Paper',
        'Denim, Bonded',
        'EVA foam',
        'Everyday Iron-On Mesh',
        'Everyday Iron-On Mosaic',
        'Everyday Iron-On',
        'Express Iron-On',
        'Faux Leather (Paper Thin)',
        'Faux Suede',
        'Felt, Wool Bonded',
        'Felt, Wool Fabric',
        'Flat Cardboard',
        'Flexible Stencil Film',
        'Flocked Paper',
        'Foil Acetate',
        'Foil Iron-On',
        'Foil Kraft Board Holographic',
        'Foil Poster Board',
        'Genuine Leather',
        'Glitter Cardstock',
        'Glitter Craft Foam',
        'Glitter Iron-On',
        'Glitter Mesh Iron-On',
        'Glow in the Dark Iron-On',
        'Glow in the Dark Vinyl',
        'Heat/Cold Activated Color Changing Vinyl',
        'Heavy Cardstock 100 lb (270 gsm)',
        'Heavy Patterned Paper',
        'Heavy Watercolor Paper 140 lbs (300 gsm)',
        'Holographic Iron-On Mosaic',
        'Holographic Iron-On',
        'Holographic Sparkle Iron-On Mosaic',
        'Holographic Sparkle Iron-On',
        'Holographic Sparkle Vinyl',
        'Holographic Vinyl',
        'Infusible Ink Transfer Sheet',
        'Insert Card - Cardstock',
        'Kraft Board',
        'Kraft Cardstock',
        'Laser Copy Paper',
        'Light Cardstock 65 lb (176 gsm)',
        'Magnetic Sheet 0.5 mm',
        'Medium Cardstock 80 lb (216 gsm)',
        'Metallic Iron-On Mosaic',
        'Metallic Leather',
        'Metallic Poster Board',
        'Mylar',
        'Natural Wood Veneer',
        'Parchment Paper',
        'Party Foil',
        'Patterned Iron-On',
        'Photo Paper',
        'Polyester, Bonded',
        'Poster Board',
        'Premium Vinyl Frosted Glitter',
        'Premium Vinyl Frosted Opaque',
        'Premium Vinyl Holographic 3D Texture',
        'Premium Vinyl Holographic Art Deco',
        'Premium Vinyl Holographic Bubbles',
        'Premium Vinyl Holographic Crystals',
        'Premium Vinyl Holographic Threads',
        'Premium Vinyl Mosaic',
        'Premium Vinyl Pearl',
        'Premium Vinyl - Permanent Glossy',
        'Premium Vinyl - Removable Matte',
        'Premium Vinyl Shimmer',
        'Premium Vinyl Textured Metallic',
        'Premium Vinyl Textured',
        'Premium Vinyl True Brushed',
        'Printable Fabric',
        'Printable Iron-On, Dark',
        'Printable Iron-On, Light',
        'Printable Sticker Paper, Clear',
        'Printable Sticker Paper, White (Gray Liner Printing)',
        'Printable Sticker Paper, White (Green Liner Printing)',
        'Printable Vinyl, Specialty',
        'Printable Vinyl, Transparent',
        'Printable Vinyl, White (Gray Liner Printing)',
        'Printable Vinyl, White (Green Liner Printing)',
        'Printable Waterproof Sticker Set - Transparent',
        'Printable Waterproof Sticker Set - Transparent Holographic',
        'Printable Waterproof Sticker Set - White',
        'Printable Waterproof Sticker Set - White Holographic',
        'Reflective Iron-On',
        'Shimmer Paper',
        'Smart Dissolvable Labels',
        'Smart Iron-On Glitter',
        'Smart Iron-On Holographic',
        'Smart Iron-On',
        'Smart Label Writable Vinyl',
        'Smart Paper Sticker Cardstock',
        'Smart Stencil',
        'Smart Vinyl Matte Metallic',
        'Smart Vinyl Permanent',
        'Smart Vinyl Removable',
        'Smart Vinyl Shimmer',
        'Smooth Glitter Paper',
        'SportFlex Iron-On',
        'Stencil Film 0.4 mm',
        'Tattoo Paper',
        'Transparency',
        'UV Activated Color Changing Iron-On',
        'Vellum',
        'Washi Sheet',
        'Watercolor Cards',
        'Wax Paper',
        'Window Cling',
        'Wrapping Paper',
      ],
      specTags: ['Bluetooth', 'USB', 'Mac', 'Windows'],
    },
    image:
      'https://cricut.com/on/demandware.static/-/Library-Sites-cricut-content-na01/default/dwa33d0d66/images/comparison/cricutVenture/machine/Machine_Cricut_Venture_Desktop.jpg',
    url: 'https://cricut.com/en-us/cutting-machines/cricut-venture/cricut-venture/cricut-venture/2008739.html',
  },
  {
    id: 6,
    name: 'Cricut Explore Air 2',
    description:
      'The go-to machine for paper crafting. Design and cut up to 24 inches for making custom cards, labels, stickers, personalized T-shirts & more.',
    tags: {
      projectTags: [
        'Vinyl decals',
        'Written labels',
        'Cards',
        'Gift tags',
        'Custom mugs',
        'Full-color stickers',
        'Personalized apparel',
        'Banners',
        'Gift boxes',
        'Signs',
        'Jewelry',
      ],
      cutTypeTags: ['Cut', 'Write', 'Draw', 'Foil', 'Score'],
      toolTags: [
        'Premium Fine-Point Blade',
        'Foil Transfer Tool',
        'Pens & Markers',
        'Deep-Point Blade',
        'Scoring Stylus',
        'Bonded-Fabric Blade',
      ],
      materialTags: [
        'Adhesive Foil',
        'Adhesive Foil, Matte',
        'Aluminum - 0.14mm',
        'Aluminum Foil',
        'Birch',
        'Burlap, Bonded*',
        'Canvas',
        'Cardstock (for intricate cuts)',
        'Chalkboard Vinyl',
        'Construction Paper',
        'Copy Paper - 20 lb (75 gsm)',
        'Copy Paper - 24 lb (90 gsm)',
        'Copy Paper - 24 lb (90 gsm)',
        'Cork, Adhesive-Backed',
        'Corrugated Cardboard',
        'Craft Foam',
        'Cutaway Card + Backer',
        'Cutting Mat Protector',
        'Deluxe Paper',
        'Deluxe Paper Foil Embossed',
        'Denim, Bonded*',
        'Distressed Craft Foam',
        'Duct Tape Sheet',
        'Epoxy Glitter Paper',
        'Everyday Iron-On',
        'Everyday Iron-On Mesh',
        'Everyday Iron-On Mosaic',
        'Express Iron-On',
        'Faux Leather (Paper Thin)',
        'Faux Suede',
        'Felt, Wool Bonded*',
        'Felt, Wool Fabric',
        'Flat Cardboard',
        'Flexible Stencil Film',
        'Flocked Paper',
        'Foil Acetate',
        'Foil Iron-On',
        'Foil Kraft Board - Holographic',
        'Foil Paper - 0.36mm',
        'Foil Poster Board',
        'Fusible Fabric',
        'Genuine Leather',
        'Glitter Cardstock',
        'Glitter Iron-On',
        'Glitter Mesh Iron-On',
        'Glitter Vinyl',
        'Grocery Bag',
        'Heavy Cardstock-100 lb (270 gsm)',
        'Heavy Patterned Paper',
        'Heavy Watercolor Paper - 140 lb (300 gsm)',
        'Holographic Iron-On',
        'Holographic Iron-On Mosaic',
        'Holographic Sparkle Iron-On',
        'Holographic Sparkle Iron-On Mosaic',
        'Holographic Sparkle Vinyl',
        'Infusible Ink Transfer Sheet',
        'Insert Card Cardstock',
        'Kraft Board',
        'Kraft Cardstock',
        'Laser Copy Paper',
        'Light Chipboard - 0.37mm',
        'Light Glitter Paper',
        'Light Patterned Paper',
        'Magnetic Sheet - 0.5mm',
        'Magnetic Sheet - 0.6mm',
        'Magnetic Sheet, Adhesive Backed - 0.35mm',
        'Medium Cardstock - 80 lb (216 gsm)',
        'Metallic Iron-On Mosaic',
        'Metallic Leather',
        'Metallic Poster Board',
        'Mylar',
        'Natural Wood Veneer',
        'Notebook Paper',
        'Oil Cloth, Bonded*',
        'Paint Chip',
        'Parchment Paper',
        'Party Foil',
        'Patterned Iron-On',
        'Pearl Paper',
        'Photo Paper',
        'Plush Craft Foam',
        'Polyester, Bonded*',
        'Premium Outdoor Vinyl',
        'Premium Vinyl',
        'Premium Vinyl-Frosted Glitter',
        'Premium Vinyl-Frosted Gray',
        'Premium Vinyl-Frosted Opaque',
        'Premium Vinyl-Holographic',
        'Premium Vinyl-Holographic 3D Texture',
        'Premium Vinyl-Holographic Art Deco',
        'Premium Vinyl-Holographic Bubbles',
        'Premium Vinyl-Holographic Crystals',
        'Premium Vinyl-Holographic Rose Bubble',
        'Premium Vinyl-Holographic Threads',
        'Premium Vinyl-Mosaic',
        'Premium Vinyl-Pearl',
        'Premium Vinyl-Shimmer',
        'Premium Vinyl-Textured',
        'Premium Vinyl-Textured Metallic',
        'Premium Vinyl-True Brushed',
        'Printable Fabric',
        'Printable Iron-On, Dark',
        'Printable Iron-On, Light',
        'Printable Sticker Paper, Clear (No Liner Printing)',
        'Printable Sticker Paper, White (Gray Liner Printing)',
        'Printable Sticker Paper, White (Green Liner Printing)',
        'Printable Vinyl, Transparent',
        'Printable Vinyl, White (Gray Liner Printing)',
        'Printable Vinyl, White (Green Liner Printing)',
        'Reflective Iron-On',
        'Shimmer Leather - 1mm',
        'Shimmer Paper',
        'Silk, Bonded*',
        'Smooth Glitter Paper',
        'Sparkle Paper',
        'SportFlex Iron-On',
        'Stencil Film - 0.4mm',
        'Stencil Vinyl',
        'Sticky Note',
        'Tattoo Paper',
        'Transparency',
        'True Brushed Paper',
        'Vellum',
        'Washi Sheet',
        'Washi Tape - 0.06mm',
        'Wax Paper',
        'Window Cling',
        'Wrapping Paper',
      ],
      specTags: ['Bluetooth', 'USB', 'iOS', 'Mac', 'Windows', 'Android'],
    },
    image:
      'https://cricut.com/on/demandware.static/-/Library-Sites-cricut-content-na01/default/dw16ed7a76/images/comparison/cricutExploreAir2/machine/Machine_Cricut_Explore_Air2_Desktop.jpg',
    url: 'https://cricut.com/en-us/search?q=cricut+explore+air+2',
  },
];
